{{- if .Values.useExternalSecrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "postfix.fullname" . }}
spec:
  backendType: {{ .Values.ExternalSecretsBackendType }}
  dataFrom:
  - {{ .Values.ExternalSecretsKey }}
{{- end -}}